site_name: Documentacion as an when foundation
site_url: https://asanwhenfoundation.org/

nav:
   - home: index.md
   - tecnologias: tecnologias usadas.md
   - problemas: problemas.md
   - organizacion: organizacion.md

theme: readthedocs